### ISSUE TITLE
Milestone 3 Reflection

### ISSUE THREAD

**Issue by mikelynch416** [UBC-MDS/Mental-Health-in-Tech-Dashboard-R#17]
# What We Have Implemented

As we mentioned in our proposal document, we wanted to make the “Mental Health in Tech Workers” dashboard in such a way that it could provide an overview of the survey data used for the dashboard but also include additional information relevant to our target audience. So far we have included these two sections in a Python dashboard we released last week as part of milestone 2 as well as in the R dashboard we're releasing this week. 

Like the Python version of the dashboard, the overview section consists of a visualization that allows the user to select a question from the survey and quickly visualize the responses and the HR questions section includes plots that each answer a specific question HR domain experts may have about the ways mental health issues affect work productivity as well as the factors which affect the rate at which productivity issues are experienced. In addition to these plots we have also implemented filters that allow users to filter the data included in the visualizations according to factors like the age and sex of survey respondents so that they can make the visualizations more closely align with the factors that exist in their workplaces (for example, with the current filters an HR domain expert could tune the visualizations to be more relevant to their predominantly male and older workforce).

# Future Improvements

For our future improvements, we would still like to include additional visualizations relevant to HR policies and how they affect mental health. For example, in our proposal's usage scenario section we indicated that we would like to be able to visualize the responses to the survey question “Does your employer provide resources to learn more about mental health issues and how to seek help?” as well as to visualize how certain other variables correlate with the occurences of survey responses indicating high levels of impact on worker productivity due to mental health issues. This would allow users to answer questions like "Does the data indicate that my proposed policy of (for example) expanding remote working options is likely to lead to a decrease in the rate of workers experiencing  mental health issues that impact their work productivity?".

Additonally, we would like to continue to add filters to the HR section based on the survey response data (ex. filters for the benefits that are available at each of the survey respondents' companies) and make sure they apply to a common dataset which all visualizations could use so that HR domain experts can accurately model the conditions that exist in their workplaces as well as gain intuition on the potential effects of the proposed policies.

Also, in our proposal we mentioned that we would like our dashboard to be tabbed but right now there is only a single page separated by sections so another future improvement would be to change over to tabbed sections. A final priority will be to apply some styling to the app since in its current state it is not very visually appealing, which could impact the user experience. 

# Thoughts on implementing the dashboard a second time using the R language

As this is the second time we have created the Mental Health in Tech dashboard, we have gained some insights in terms of the differences between using Python and R for building dashboards. Notably among those is the difference in how the app was deployed. In both cases we used the cloud platform Heroku for deploying the dashboard, but the difference this time is that while Heroku supports the Python programming language it does not normally support R. In our experience this added some complexity to the deployment process, as this time we needed to use a linux container ... (insert new steps that were required).

**Comment by fatse** [comment]
We needed to use a Docker container that would allow us to install and use R libraries in the Heroku server; normally when we used Python we did that from the `requirements.txt` file. To achieve this, we had to add `init.R` and `apt-packages` files which Docker image uses in order to perform the installations needed for an R environment. Also, we had to move our `app.R` script from the `src` folder into the root directory - leaving `app.R` in the `src` folder would potentially cause problems if not configured correctly in the Docker image. Moving `app.R` to the root directory is not ideal because it doesn't conform to the standardized best practices for better organizing project files. Also, we had to specify for Heroku to create an application using a Docker container with the command `heroku create --stack container <app-name>` which is an extra step compared to the Python app. And finally, the deployment process itself lasted approximately 15 minutes, which is substantially longer compared to the Python project deployment.
